feat: popup when link does not exist
jannisborn/PennyMe pull request #112
Opened 2023-08-10 21:59 UTC by jannisborn

Closes #111

2023-08-10 22:17 UTC, NinaWie requested changes

2023-08-10 22:17 UTC, NinaWie commented on PennyMe/Base.lproj/Main.storyboard
> +                                                <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="Further informati
Maybe we should call it "More info at pennycollector.com". I agree that "external website" sounds weird, but I think it's annoying when you click on a button in an app and suddently you're in the browser. So I don't like "Further infromation that much"

2023-08-10 22:17 UTC, NinaWie commented on PennyMe/PinViewController.swift
> +            print(pinData.link, pinData.link.contains("http"))
Maybe we should remove the print statement

2023-08-12 05:17 UTC, jannisborn commented
Called it now "More details on pennycollector.com". 
"Information" is too long and "info" is a bit to informal IMHO

Please have a look again @NinaWie

2023-08-14 12:33 UTC, NinaWie approved these changes

2023-08-14 12:33 UTC, merged