add new machine 6020 named Herrschaftszeiten – Das Paulaner im Tal
jannisborn/PennyMe pull request #114
Opened 2023-08-12 11:15 UTC by NinaWie

New machine submitted for review

2023-08-12 22:10 UTC, jannisborn requested changes

2023-08-13 22:01 UTC, jannisborn approved these changes

2023-08-13 22:02 UTC, jannisborn commented
I dont find the picture very convincing since it only shows a penny but not a machine! Any idea who proposed it @NinaWie

2023-08-14 12:31 UTC, NinaWie commented
No idea who proposed it, cool that it's in Munich! From my side it's fine to merge it, there is a picture of a beer on the coin and I think it's realistic that there is a machine. We have to trust the users to some extent :)

2023-08-14 22:09 UTC, merged